apiVersion: batch/v1
kind: Job
metadata:
  generateName: dummyjob
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "0"
spec:
  template:
    spec:
      containers:
        - name: dummyjob
          image: alpine:latest
          command: ["sleep", "5"]
      restartPolicy: Never
