apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnerable-nginx
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: vulnerable-nginx
  template:
    metadata:
      labels:
        app: vulnerable-nginx
    spec:
      containers:
      - image: docker.io/nginx
        name: vulnerable-nginx
        ports:
        - containerPort: 80